# Generated by Django 4.2.16 on 2024-12-24 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_password', models.CharField(default='000000', help_text='Standard access password (6 digits).', max_length=6)),
                ('admin_password', models.CharField(default='123456', help_text='Admin access password (6 digits).', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the access code was created.')),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value', models.CharField(help_text='API key value.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the API key was created.')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(help_text='email name.', max_length=100)),
                ('smtp_server', models.CharField(help_text='SMTP server address.', max_length=100)),
                ('host_user', models.CharField(help_text='Email host user.', max_length=100)),
                ('host_password', models.CharField(help_text='Email host password.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the configuration was created.')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductory_text', models.TextField(blank=True, help_text='Introductory text for the document.', null=True)),
                ('default_footer', models.TextField(blank=True, help_text='Default footer text.', null=True)),
                ('general_terms', models.TextField(blank=True, help_text='General terms and conditions.', null=True)),
                ('late_interest', models.CharField(blank=True, help_text='Interest rate or penalties for late payments.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the configuration was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the configuration was last updated.')),
            ],
            options={
                'verbose_name': 'Invoice Configuration',
                'verbose_name_plural': 'Invoice Configurations',
            },
        ),
        migrations.CreateModel(
            name='QuoteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductory_text', models.TextField(blank=True, help_text='Introductory text for the document.', null=True)),
                ('default_footer', models.TextField(blank=True, help_text='Default footer text.', null=True)),
                ('general_terms', models.TextField(blank=True, help_text='General terms and conditions.', null=True)),
                ('late_interest', models.CharField(blank=True, help_text='Interest rate or penalties for late payments.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the configuration was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the configuration was last updated.')),
            ],
            options={
                'verbose_name': 'Quote Configuration',
                'verbose_name_plural': 'Quote Configurations',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_url', models.CharField(help_text='URL for the operator.', max_length=255, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the URL was created.')),
            ],
        ),
    ]
