# Generated by Django 4.2.16 on 2024-12-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrages', '0001_initial'),
        ('configurations', '0002_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteconfiguration',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configurations', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='quoteconfiguration',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, help_text='Default payment method associated with this configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_default_payment_methods', to='configurations.paymentmethod'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configurations', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, help_text='Default payment method associated with this configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_default_payment_methods', to='configurations.paymentmethod'),
        ),
    ]
