# Generated by Django 4.2.16 on 2025-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('simple_transfer', 'Transfert Simple'), ('made_available', 'Mise à Disposition')], help_text='Type de TVA (Transfert Simple ou Mise à Disposition).', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de TVA en pourcentage (10% par défaut).', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Description de la TVA.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la TVA.')),
            ],
        ),
    ]
