# Generated by Django 4.2.16 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrages', '0003_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(help_text='Description du service de voiture de transport avec chauffeur.')),
                ('legal_notice_1', models.TextField(help_text='Première mention légale (Billet collectif : Arrêté du 14 Février 1986 - Article 5).')),
                ('legal_notice_2', models.TextField(help_text='Deuxième mention légale (Ordre de mission : Arrêté du 6 Janvier 1993 - Article 3).')),
                ('vehicle_rental_description', models.TextField(help_text='Description de la location de véhicule avec chauffeur.')),
                ('pricing_details', models.TextField(help_text='Détails sur les tarifs et les conditions de facturation.')),
                ('default_footer', models.TextField(default='', help_text='Contenu du pied de page pour les PDF.')),
            ],
        ),
    ]
