# Generated by Django 4.2.18 on 2025-01-22 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrages', '0004_staticcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='interface_url',
            field=models.CharField(blank=True, help_text='URL for the operator.', max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
