# Generated by Django 4.2.16 on 2024-12-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_driver_company_driver_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='joint_key',
        ),
        migrations.AddField(
            model_name='agency',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='utilisateurs.client'),
        ),
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='companies', to='utilisateurs.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('simple', 'Client Simple'), ('agency', 'Agence'), ('company', 'Société'), ('agency_agent', 'Agent lié à une agence'), ('company_collaborator', 'Collaborateur lié à une société'), ('is_partial', 'Client Partiel')], default='simple', max_length=50),
        ),
    ]
