# Generated by Django 4.2.16 on 2024-12-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AddField(
            model_name='client',
            name='joint_key',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='utilisateurs.client'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
