# Generated by Django 4.2.18 on 2025-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_customuser_otp_code_customuser_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='joint_key',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
