# Generated by Django 4.2.16 on 2025-01-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='destinationInputs',
            field=models.JSONField(blank=True, help_text='Waypoints locations.', null=True),
        ),
    ]
