# Generated by Django 4.2.16 on 2025-01-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_estimate_destinationinputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(help_text='ID of the tariff rule.')),
                ('calculated_cost', models.FloatField(help_text='Calculated cost after applying the rule.')),
            ],
        ),
        migrations.CreateModel(
            name='EstimationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(help_text='Lieu de départ.', max_length=255)),
                ('destination', models.CharField(help_text='Lieu de destination.', max_length=255)),
                ('pickup_date', models.DateTimeField(help_text='Date et heure de prise en charge.')),
                ('waypoints', models.JSONField(blank=True, help_text="Points d'étape (optionnel).", null=True)),
                ('estimate_type', models.CharField(choices=[('simple_transfer', 'Transfert Simple'), ('made_available', 'Mise à Disposition')], default='simple_transfer', help_text="Type d'estimation (Transfert Simple ou Mise à Disposition).", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'estimation.")),
                ('is_booked', models.BooleanField(default=False, help_text="Indique si l'estimation a été convertie en réservation.")),
                ('distance_travelled', models.FloatField(help_text='Distance parcourue en kilomètres.')),
                ('duration_travelled', models.CharField(help_text='Durée du trajet.', max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'estimation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(help_text='ID of the vehicle.')),
                ('standard_cost', models.FloatField(help_text='Standard cost of the vehicle (without rules).')),
                ('rules', models.JSONField(default=dict, help_text='List of tariff rule IDs applied, divided into promos and others.')),
                ('applied_tariffs', models.ManyToManyField(help_text='List of calculated tariffs after applying rules.', related_name='estimation_tariffs', to='courses.appliedtariff')),
                ('estimation_log', models.ForeignKey(help_text='Estimation associated with this tariff.', on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='courses.estimationlog')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(help_text='ID of the selected vehicle.')),
                ('is_standard_cost', models.BooleanField(default=False, help_text='Indicates if the selected tariff is the standard cost.')),
                ('selected_tariff', models.ForeignKey(blank=True, help_text='Selected tariff (if not standard cost).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.appliedtariff')),
            ],
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='departure_location',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='destinationInputs',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='distance_travelled',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='duration_travelled',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='estimated_transport_costs',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='transport_cost',
        ),
        migrations.DeleteModel(
            name='TransportCost',
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimation_log',
            field=models.OneToOneField(help_text='Log associated with this estimate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='courses.estimationlog'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='user_choice',
            field=models.ForeignKey(blank=True, help_text="User's choice of vehicle and tariff.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='courses.userchoice'),
        ),
    ]
