# Generated by Django 4.2.16 on 2025-01-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_alter_tariffrule_priority'),
        ('courses', '0004_appliedtariff_estimationlog_estimationtariff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationtariff',
            name='rules',
        ),
        migrations.AddField(
            model_name='estimationtariff',
            name='rules',
            field=models.ManyToManyField(help_text='List of tariff rules applied to this estimation.', related_name='estimation_tariffs', to='configurations.tariffrule'),
        ),
    ]
