# Generated by Django 4.2.16 on 2025-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_estimationtariff_rules_estimationtariff_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateattribute',
            name='estimation',
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_attribute',
            field=models.ManyToManyField(help_text='Attribute associated with this estimate.', related_name='estimates', to='courses.estimateattribute'),
        ),
    ]
