# Generated by Django 4.2.16 on 2025-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_estimateattribute_estimation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='commission',
            field=models.FloatField(blank=True, help_text='Commission amount.', null=True),
        ),
    ]
