# Generated by Django 4.2.18 on 2025-05-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_booking_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedtariff',
            name='admin_user_id',
            field=models.IntegerField(blank=True, help_text="ID de l'admin créateur", null=True),
        ),
        migrations.AddField(
            model_name='appliedtariff',
            name='is_admin_custom',
            field=models.BooleanField(default=False, help_text='Tarif créé par modification admin'),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='admin_custom_price',
            field=models.FloatField(blank=True, help_text="Prix personnalisé saisi par l'admin", null=True),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='admin_user_id',
            field=models.IntegerField(blank=True, help_text="ID de l'admin qui a modifié le prix", null=True),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='is_admin_custom',
            field=models.BooleanField(default=False, help_text='Indique si un prix admin a été appliqué'),
        ),
    ]
