# Generated by Django 4.2.18 on 2025-05-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_appliedtariff_admin_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedtariff',
            name='admin_user_id',
        ),
        migrations.RemoveField(
            model_name='appliedtariff',
            name='is_admin_custom',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='admin_custom_price',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='admin_user_id',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='is_admin_custom',
        ),
    ]
