# Generated by Django 4.2.18 on 2025-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_appliedtariff_admin_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_payment_pending',
            field=models.BooleanField(default=False),
        ),
    ]
