# Generated by Django 4.2.18 on 2025-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_estimate_is_payment_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the passenger.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_main_client',
            field=models.BooleanField(default=False, help_text='Indicates if this passenger is the main client.'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
