# Generated by Django 4.2.18 on 2025-06-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_client_joint_key'),
        ('courses', '0011_passenger_email_passenger_is_main_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associated with this passenger.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='utilisateurs.client'),
        ),
    ]
