# Generated by Django 4.2.18 on 2025-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_passenger_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_timing',
            field=models.CharField(choices=[('later', 'Deferred Payment'), ('now', 'Immediate Payment')], default='later', help_text='Indique quand le paiement sera effectué', max_length=10),
        ),
    ]
