# Generated by Django 4.2.18 on 2025-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_booking_payment_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='payment_notes',
            field=models.CharField(blank=True, help_text='payment notes associated with the payment method.', max_length=250, null=True),
        ),
    ]
