# Generated by Django 4.2.18 on 2025-06-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_estimate_payment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='payment_notes',
        ),
    ]
