# Generated by Django 4.2.18 on 2025-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_estimate_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indicates if the booking has been archived.'),
        ),
    ]
