# Generated by Django 4.2.18 on 2025-07-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_booking_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('assigned_to_driver', 'Assigned to Driver'), ('assigned_to_partner', 'Assigned to Partner'), ('not_assigned', 'Not Assigned'), ('driver_notified', 'Driver Notified'), ('approaching', 'Approaching'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Status of the booking.', max_length=25),
        ),
    ]
