# Generated by Django 4.2.18 on 2025-07-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('one_way', 'Aller simple'), ('round_trip', 'Aller-retour')], default='one_way', help_text='Type de réservation (simple ou aller-retour)', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('outbound', 'Aller'), ('return', 'Retour')], help_text='Type de segment (aller ou retour)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('assigned_to_driver', 'Assigned to Driver'), ('assigned_to_partner', 'Assigned to Partner'), ('not_assigned', 'Not Assigned'), ('driver_notified', 'Driver Notified'), ('approaching', 'Approaching'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Statut du segment', max_length=25)),
                ('segment_cost', models.FloatField(blank=True, help_text='Coût de ce segment', null=True)),
                ('compensation', models.FloatField(blank=True, help_text='Compensation pour ce segment', null=True)),
                ('commission', models.FloatField(blank=True, help_text='Commission pour ce segment', null=True)),
                ('order', models.PositiveIntegerField(help_text='Ordre du segment (1=aller, 2=retour)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du segment')),
                ('booking', models.ForeignKey(help_text='Booking parent contenant ce segment', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='courses.booking')),
                ('estimate', models.ForeignKey(help_text='Estimation associée à ce segment', on_delete=django.db.models.deletion.CASCADE, related_name='booking_segments', to='courses.estimate')),
            ],
            options={
                'verbose_name': 'Segment de réservation',
                'verbose_name_plural': 'Segments de réservation',
                'ordering': ['order'],
                'unique_together': {('booking', 'segment_type')},
            },
        ),
    ]
