# Generated by Django 4.2.18 on 2025-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_booking_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_billable_when_cancelled',
            field=models.BooleanField(default=False, help_text="Si True, ce segment reste facturable même s'il est annulé"),
        ),
        migrations.AddField(
            model_name='bookingsegment',
            name='is_billable_when_cancelled',
            field=models.BooleanField(default=False, help_text="Si True, ce segment reste facturable même s'il est annulé"),
        ),
        migrations.AddField(
            model_name='bookingsegment',
            name='is_driver_paid_segment',
            field=models.BooleanField(default=False, help_text='Indique si le chauffeur est payé pour ce segment'),
        ),
        migrations.AddField(
            model_name='bookingsegment',
            name='is_partner_paid_segment',
            field=models.BooleanField(default=False, help_text='Indique si le partenaire est payé pour ce segment'),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='commission',
            field=models.FloatField(blank=True, help_text='Commission pour ce segment (en %)', null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='compensation',
            field=models.FloatField(blank=True, help_text='Compensation pour ce segment (en €)', null=True),
        ),
    ]
