# Generated by Django 4.2.16 on 2024-12-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(help_text='Type de véhicule', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='configurations.vehicletype'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='classic_package',
            field=models.ForeignKey(blank=True, help_text='Associated classic package.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.classicpackage'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='excluded_clients',
            field=models.ManyToManyField(blank=True, help_text='Clients excluded from this tariff rule.', related_name='excluded_tariff_rules', to='utilisateurs.client'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='fixed_adjustment',
            field=models.ForeignKey(blank=True, help_text='Associated fixed adjustment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.fixedadjustment'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Associated promo code.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.promocode'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='radius_package',
            field=models.ForeignKey(blank=True, help_text='Associated radius package.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.radiuspackage'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='scheduled_adjustment',
            field=models.ForeignKey(blank=True, help_text='Associated scheduled adjustment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.scheduledadjustment'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='specific_clients',
            field=models.ManyToManyField(blank=True, help_text='Specific clients allowed (only if available_to_all=False).', related_name='specific_tariff_rules', to='utilisateurs.client'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='vehicle',
            field=models.ForeignKey(help_text='Vehicle this tariff rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configurations', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_method',
            field=models.OneToOneField(help_text='Associated payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
        migrations.AddField(
            model_name='scheduledadjustment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='radiuspackage',
            name='vehicle',
            field=models.ForeignKey(help_text='Vehicle this package applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_package_related', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business linked to this promo code.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle this promo code applies to, otherwise applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='price',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configurations', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='payment_method',
            field=models.OneToOneField(help_text='Associated payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='fixedadjustment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='classicpackage',
            name='vehicle',
            field=models.ForeignKey(help_text='Vehicle this package applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_package_related', to='configurations.vehicle'),
        ),
        migrations.AddField(
            model_name='banktransferpayment',
            name='business',
            field=models.ForeignKey(help_text='Business associated with this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configurations', to='utilisateurs.business'),
        ),
        migrations.AddField(
            model_name='banktransferpayment',
            name='payment_method',
            field=models.OneToOneField(help_text='Associated payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.business'),
        ),
    ]
