# Generated by Django 4.2.16 on 2024-12-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='configurations.price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cargo_capacity',
            field=models.CharField(max_length=255),
        ),
    ]
