# Generated by Django 4.2.16 on 2024-12-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_remove_price_vehicle_vehicle_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='cargo_capacity',
            new_name='luggage_capacity',
        ),
    ]
