# Generated by Django 4.2.16 on 2024-12-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_rename_cargo_capacity_vehicle_luggage_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('increase', 'Increase')], default='discount', help_text='Type of adjustment', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage to apply (positive for increase, negative for discount)', max_digits=5, null=True)),
                ('fixed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed value to add or subtract', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Flat rate.', max_digits=10)),
                ('departure_latitude', models.DecimalField(decimal_places=6, help_text='Departure point latitude.', max_digits=9)),
                ('departure_longitude', models.DecimalField(decimal_places=6, help_text='Departure point longitude.', max_digits=9)),
                ('arrival_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Arrival point latitude.', max_digits=9, null=True)),
                ('arrival_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Arrival point longitude.', max_digits=9, null=True)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Central point latitude.', max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Central point longitude.', max_digits=9, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, help_text='Radius in kilometers around the central point.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fixedadjustment',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='radiuspackage',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='scheduledadjustment',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='active',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='applicable_days',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='tariffrule',
            name='classic_package',
        ),
        migrations.RemoveField(
            model_name='tariffrule',
            name='fixed_adjustment',
        ),
        migrations.RemoveField(
            model_name='tariffrule',
            name='radius_package',
        ),
        migrations.RemoveField(
            model_name='tariffrule',
            name='scheduled_adjustment',
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='action_type',
            field=models.CharField(blank=True, choices=[('scheduled_adjustment', 'Scheduled Adjustment'), ('fixed_adjustment', 'Fixed Adjustment'), ('classic_package', 'Classic Package'), ('radius_package', 'Radius Package'), ('promo_code', 'Promo Code')], help_text='Type of the action ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='application_date',
            field=models.DateField(blank=True, help_text='Specific date for application', null=True),
        ),
        migrations.AlterField(
            model_name='tariffrule',
            name='promo_code',
            field=models.OneToOneField(blank=True, help_text='Associated promo code.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.promocode'),
        ),
        migrations.AlterField(
            model_name='tariffrule',
            name='rule_type',
            field=models.CharField(blank=True, choices=[('adjustment', 'Réduction/Majoration'), ('package', 'Forfait'), ('promo_code', 'Code Promo')], help_text='Type of the tariff rule (adjustment, package, promo code, etc.).', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ClassicPackage',
        ),
        migrations.DeleteModel(
            name='FixedAdjustment',
        ),
        migrations.DeleteModel(
            name='RadiusPackage',
        ),
        migrations.DeleteModel(
            name='ScheduledAdjustment',
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='adjustment',
            field=models.OneToOneField(blank=True, help_text='Associated adjustment (discount or increase).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.adjustment'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='package',
            field=models.OneToOneField(blank=True, help_text='Associated package (fixed rate or radius).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='configurations.package'),
        ),
    ]
