# Generated by Django 4.2.16 on 2024-12-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_adjustment_package_remove_fixedadjustment_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la notification.', max_length=255)),
                ('message', models.TextField(help_text='Contenu de la notification.')),
                ('type', models.CharField(choices=[('expiration', 'Expiration'), ('usage_limit', "Limite d'utilisation atteinte")], help_text="Type de la notification (expiration, limite d'utilisation, etc.).", max_length=50)),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('archived', 'Archivée')], default='unread', help_text='Statut de la notification (non lue, archivée).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification.')),
                ('archived_at', models.DateTimeField(blank=True, help_text="Date d'archivage de la notification.", null=True)),
                ('related_rule', models.ForeignKey(blank=True, help_text='Règle tarifaire liée à la notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='configurations.tariffrule')),
            ],
        ),
    ]
