# Generated by Django 4.2.16 on 2025-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('radius', 'Radius')], default='classic', help_text='Type of package', max_length=20),
        ),
    ]
