# Generated by Django 4.2.16 on 2025-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_package_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffrule',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Priority of the tariff rule (1 = lowest priority).'),
        ),
    ]
