# Generated by Django 4.2.18 on 2025-02-26 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_alter_tariffrule_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferpayment',
            name='payment_method',
            field=models.ForeignKey(help_text='Associated payment method.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paypalpayment',
            name='payment_method',
            field=models.ForeignKey(help_text='Associated payment method.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_method',
            field=models.ForeignKey(help_text='Associated payment method.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_configuration', to='configurations.paymentmethod'),
        ),
    ]
