# Generated by Django 4.2.18 on 2025-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_alter_banktransferpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this payment method active?'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
