# Generated by Django 4.2.18 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_alter_paymentmethod_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
