# Generated by Django 4.2.18 on 2025-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0014_alter_package_arrival_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('expiration', 'Expiration'), ('usage_limit', "Limite d'utilisation atteinte"), ('booking_confirmation', 'Confirmation de réservation'), ('booking_update', 'Mise à jour de réservation')], help_text="Type de la notification (expiration, limite d'utilisation, etc.).", max_length=50),
        ),
    ]
